// login action typed
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

// signup action types
export const SIGNUP_REQUEST = 'SIGNUP_REQUEST';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE';
export const LOGOUT = 'LOGOUT';

// all users action types
export const GET_ALL_USERS_REQUEST = 'GET_ALL_USERS_REQUEST';
export const GET_ALL_USERS_SUCCESS = 'GET_ALL_USERS_SUCCESS';
export const GET_ALL_USERS_FAILURE = 'GET_ALL_USERS_FAILURE';
// user profile actions
export const GET_USER_PROFILE_REQUEST = 'GET_USER_PROFILE_REQUEST';
export const GET_USER_PROFILE_SUCCESS = 'GET_USER_PROFILE_SUCCESS';
export const GET_USER_PROFILE_FAILURE = 'GET_USER_PROFILE_FAILURE';



//BRAND action types
export const CREATE_BRAND_SUCCESS = 'CREATE_BRAND_SUCCESS';
export const CREATE_BRAND_FAILURE = 'CREATE_BRAND_FAILURE';
export const GET_BRANDS_SUCCESS = 'GET_BRANDS_SUCCESS';
export const GET_BRANDS_FAILURE = 'GET_BRANDS_FAILURE';
export const GET_BRAND_SUCCESS = 'GET_BRAND_SUCCESS';
export const GET_BRAND_FAILURE = 'GET_BRAND_FAILURE';
export const UPDATE_BRAND_SUCCESS = 'UPDATE_BRAND_SUCCESS';
export const UPDATE_BRAND_FAILURE = 'UPDATE_BRAND_FAILURE';
export const DELETE_BRAND_SUCCESS = 'DELETE_BRAND_SUCCESS';
export const DELETE_BRAND_FAILURE = 'DELETE_BRAND_FAILURE';

// concern person action types
export const CREATE_CONCERNPERSON_SUCCESS = 'CREATE_CONCERNPERSON_SUCCESS';
export const CREATE_CONCERNPERSON_FAILURE = 'CREATE_CONCERNPERSON_FAILURE';
export const GET_CONCERNPERSONS_SUCCESS = ' GET_CONCERNPERSONS_SUCCESS';
export const GET_CONCERNPERSONS_FAILURE= 'GET_CONCERNPERSONS_FAILURE';
export const GET_CONCERNPERSON_SUCCESS = 'GET_CONCERNPERSON_SUCCESS';
export const GET_CONCERNPERSON_FAILURE = 'GET_CONCERNPERSON_FAILURE';
export const UPDATE_CONCERNPERSON_SUCCESS = 'UPDATE_CONCERNPERSON_SUCCESS';
export const UPDATE_CONCERNPERSON_FAILURE = 'UPDATE_CONCERNPERSON_FAILURE';
export const DELETE_CONCERNPERSON_SUCCESS = 'DELETE_CONCERNPERSON_SUCCESS';
export const DELETE_CONCERNPERSON_FAILURE = 'DELETE_CONCERNPERSON_FAILURE';


// meeting action types
export const CREATE_MEETING_SUCCESS = 'CREATE_MEETING_SUCCESS';
export const CREATE_MEETING_FAILURE = 'CREATE_MEETING_FAILURE';
export const GET_MEETINGS_SUCCESS = 'GET_MEETINGS_SUCCESS';
export const GET_MEETINGS_FAILURE = 'GET_MEETINGS_FAILURE';
export const GET_MEETING_SUCCESS = 'GET_MEETING_SUCCESS';
export const GET_MEETING_FAILURE = 'GET_MEETING_FAILURE';



// get meeting by userid 
export const FETCH_MEETINGS_REQUEST = 'FETCH_MEETINGS_REQUEST';
export const FETCH_MEETINGS_SUCCESS = 'FETCH_MEETINGS_SUCCESS';
export const FETCH_MEETINGS_FAILURE = 'FETCH_MEETINGS_FAILURE';


// get sheet data
export const FETCH_SHEET_DATA_SUCCESS = 'FETCH_SHEET_DATA_SUCCESS';
export const FETCH_SHEET_DATA_FAILURE = 'FETCH_SHEET_DATA_FAILURE';

 // 
 //exhibition collection action types
export const CREATE_COLLECTION_SUCCESS = 'CREATE_COLLECTION_SUCCESS';
export const CREATE_COLLECTION_FAILURE = 'CREATE_COLLECTION_FAILURE';
export const GET_COLLECTIONS_SUCCESS = 'GET_COLLECTIONS_SUCCESS';
export const GET_COLLECTIONS_FAILURE = 'GET_COLLECTIONS_FAILURE';
export const GET_COLLECTION_SUCCESS = 'GET_COLLECTION_SUCCESS';
export const GET_COLLECTION_FAILURE = 'GET_COLLECTION_FAILURE';
export const UPDATE_COLLECTION_SUCCESS = 'UPDATE_COLLECTION_SUCCESS';
export const UPDATE_COLLECTION_FAILURE = 'UPDATE_COLLECTION_FAILURE';
export const DELETE_COLLECTION_REQUEST = 'DELETE_COLLECTION_REQUEST';
export const DELETE_COLLECTION_SUCCESS = 'DELETE_COLLECTION_SUCCESS';
export const DELETE_COLLECTION_FAILURE = 'DELETE_BRAND_FAILURE';
// exhibition collection by user  
export const GET_COLLECTION_BY_USER_REQUEST = 'GET_COLLECTION_BY_USER_REQUEST';
export const GET_COLLECTION_BY_USER_SUCCESS = 'GET_COLLECTION_BY_USER_SUCCESS';
export const GET_COLLECTION_BY_USER_FAILURE = 'GET_COLLECTION_BY_USER_FAILURE';



// scan codes action types
export const CREATE_SCAN_CODE_SUCCESS = 'CREATE_SCAN_CODES_SUCCESS';
export const CREATE_SCAN_CODE_FAILURE = 'CREATE_SCAN_CODES_FAILURE';
export const GET_SCAN_CODES_SUCCESS = 'GET_SCAN_CODES_SUCCESS';
export const GET_SCAN_CODES_FAILURE = 'GET_SCAN_CODES_FAILURE';
export const GET_SCAN_CODE_REQUEST = 'GET_SCAN_CODE_REQUEST';
export const GET_SCAN_CODE_SUCCESS = 'GET_SCAN_CODE_SUCCESS';
export const GET_SCAN_CODE_FAILURE = 'GET_SCAN_CODE_FAILURE';
export const UPDATE_SCAN_CODE_SUCCESS = 'UPDATE_SCAN_CODE_SUCCESS';
export const UPDATE_SCAN_CODE_FAILURE = 'UPDATE_SCAN_CODE_FAILURE';
export const DELETE_SCAN_CODE_SUCCESS = 'DELETE_SCAN_CODE_SUCCESS';
export const DELETE_SCAN_CODE_FAILURE = 'DELETE_SCAN_CODE_FAILURE';
