// login action typed
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

// signup action types
export const SIGNUP_REQUEST = 'SIGNUP_REQUEST';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE';
export const LOGOUT = 'LOGOUT';

//brabd action types
export const CREATE_BRAND_SUCCESS = 'CREATE_BRAND_SUCCESS';
export const CREATE_BRAND_FAILURE = 'CREATE_BRAND_FAILURE';
export const GET_BRANDS_SUCCESS = 'GET_BRANDS_SUCCESS';
export const GET_BRANDS_FAILURE = 'GET_BRANDS_FAILURE';
export const GET_BRAND_SUCCESS = 'GET_BRAND_SUCCESS';
export const GET_BRAND_FAILURE = 'GET_BRAND_FAILURE';
export const UPDATE_BRAND_SUCCESS = 'UPDATE_BRAND_SUCCESS';
export const UPDATE_BRAND_FAILURE = 'UPDATE_BRAND_FAILURE';
export const DELETE_BRAND_SUCCESS = 'DELETE_BRAND_SUCCESS';
export const DELETE_BRAND_FAILURE = 'DELETE_BRAND_FAILURE';

// concern person action types
export const CREATE_CONCERNPERSON_SUCCESS = 'CREATE_CONCERNPERSON_SUCCESS';
export const CREATE_CONCERNPERSON_FAILURE = 'CREATE_CONCERNPERSON_FAILURE';
export const GET_CONCERNPERSONS_SUCCESS = ' GET_CONCERNPERSONS_SUCCESS';
export const GET_CONCERNPERSONS_FAILURE= 'GET_CONCERNPERSONS_FAILURE';
export const GET_CONCERNPERSON_SUCCESS = 'GET_CONCERNPERSON_SUCCESS';
export const GET_CONCERNPERSON_FAILURE = 'GET_CONCERNPERSON_FAILURE';
export const UPDATE_CONCERNPERSON_SUCCESS = 'UPDATE_CONCERNPERSON_SUCCESS';
export const UPDATE_CONCERNPERSON_FAILURE = 'UPDATE_CONCERNPERSON_FAILURE';
export const DELETE_CONCERNPERSON_SUCCESS = 'DELETE_CONCERNPERSON_SUCCESS';
export const DELETE_CONCERNPERSON_FAILURE = 'DELETE_CONCERNPERSON_FAILURE';


// meeting action types
export const CREATE_MEETING_SUCCESS = 'CREATE_MEETING_SUCCESS';
export const CREATE_MEETING_FAILURE = 'CREATE_MEETING_FAILURE';
export const GET_MEETINGS_SUCCESS = 'GET_MEETINGS_SUCCESS';
export const GET_MEETINGS_FAILURE = 'GET_MEETINGS_FAILURE';
export const GET_MEETING_SUCCESS = 'GET_MEETING_SUCCESS';
export const GET_MEETING_FAILURE = 'GET_MEETING_FAILURE';



// get meeting by userid 
export const FETCH_MEETINGS_REQUEST = 'FETCH_MEETINGS_REQUEST';
export const FETCH_MEETINGS_SUCCESS = 'FETCH_MEETINGS_SUCCESS';
export const FETCH_MEETINGS_FAILURE = 'FETCH_MEETINGS_FAILURE';